language: go
go: 
 - tip
script:
 - go build
 - go test -v ./...
deploy:
  provider: releases
  api_key: 9ce0e51ae038aa4b1cedeb8805cb9082f866c31d
  file: sqrt
  skip_cleanup: true
  on:
    tags: master
